In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from pycaret.classification import *
from xgboost import XGBRegressor

In [2]:
df = pd.read_csv("C:\\Users\\ripa_\\Desktop\\Programing\\IndyCar_Project\\LigaMX\\datasets\\LigaMX_dataset_v2.csv")

In [3]:
df["Date"] = pd.to_datetime(df["Date"])
df = df.sort_values(["Date", "Equipo"])

In [4]:
df.head()

,Date,Time,Round,Day,Venue,Opponent,Referee,Equipo,Torneo,Temporada,...,TeamAwayForm5,OpponentForm5,OpponentWinRate5,OpponentSeasonPts,OpponentHomeForm5,OpponentAwayForm5,H2HWinRate,H2HLast5,FormDiff,SeasonPtsDiff
0,2014-07-18,19:30,Jornada 1,Fri,Away,Tijuana,Luis Santander,Puebla,Apertura,2014,...,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0
1,2014-07-18,19:30,Jornada 1,Fri,Away,Queretaro,Erick Yair Miranda,Pumas UNAM,Apertura,2014,...,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0
2,2014-07-18,19:30,Jornada 1,Fri,Home,Pumas UNAM,Erick Yair Miranda,Queretaro,Apertura,2014,...,NaN,NaN,0.0,0.0,NaN,NaN,0.0,0.0,NaN,0.0
3,2014-07-18,19:30,Jornada 1,Fri,Home,Puebla,Luis Santander,Tijuana,Apertura,2014,...,NaN,NaN,0.0,0.0,NaN,NaN,0.0,0.0,NaN,0.0
4,2014-07-19,21:00,Jornada 1,Sat,Home,Tigres UANL,Erim Ramírez,Atlas,Apertura,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
drop_cols = [
    "Date", "Time", "Round", "Day", "Venue", "Opponent", "Referee", "Equipo", "Torneo", "Temporada", "Result", "Points"
]

cutoff = df["Date"].quantile(0.95)
data = df[df["Date"] < cutoff].drop(columns=drop_cols)
data_unseen = df[df["Date"] >= cutoff].drop(columns=drop_cols)

print(data.corr(numeric_only=True)["ResultID"].sort_values())

OponentElo          -0.111290
OpponentAwayForm5   -0.028225
DayID               -0.025453
OpponentSeasonPts   -0.025366
OpponentForm5       -0.018891
OpponentWinRate5    -0.017448
TemporadaID         -0.008711
TorneoID            -0.008469
RoundID             -0.005759
TeamID              -0.000310
OpponentHomeForm5    0.000894
RefereeID            0.007649
TimeID               0.014496
TeamSeasonPts        0.020128
TeamHomeForm5        0.026066
OpponentID           0.029431
TeamWinRate5         0.049675
TeamAwayForm5        0.053529
H2HWinRate           0.054620
TeamForm5            0.057766
FormDiff             0.059044
SeasonPtsDiff        0.072725
VenueID              0.108383
H2HLast5             0.123514
TeamElo              0.141042
EloDiff              0.181458
ResultID             1.000000
Name: ResultID, dtype: float64

In [6]:
df = df.drop(columns=drop_cols)

In [7]:
print(df.columns.tolist())

['VenueID', 'OpponentID', 'TeamID', 'RefereeID', 'RoundID', 'TemporadaID', 'TorneoID', 'TimeID', 'DayID', 'ResultID', 'TeamElo', 'OponentElo', 'EloDiff', 'TeamForm5', 'TeamWinRate5', 'TeamSeasonPts', 'TeamHomeForm5', 'TeamAwayForm5', 'OpponentForm5', 'OpponentWinRate5', 'OpponentSeasonPts', 'OpponentHomeForm5', 'OpponentAwayForm5', 'H2HWinRate', 'H2HLast5', 'FormDiff', 'SeasonPtsDiff']

In [8]:
exp = setup(
    data=data, 
    target="ResultID", 
    session_id=123, 
    fold_strategy="timeseries",
    data_split_shuffle=False,
    data_split_stratify=False,
    fold_shuffle=False
)

In [ ]:
compare_models()

In [9]:
cat = create_model('catboost')

In [10]:
cat_tune = tune_model(cat)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

In [ ]:
predict_model(cat_tune);
#predict_model(cat);

In [ ]:
newpred = predict_model(cat_tune, data=data_unseen)
#newpred = predict_model(cat, data=data_unseen)

In [ ]:
rf = create_model('rf')

In [ ]:
rf_tune = tune_model(rf)

In [ ]:
predict_model(rf_tune);
#predict_model(rf);

In [ ]:
newpred = predict_model(rf_tune, data=data_unseen)
#newpred = predict_model(rf, data=data_unseen)

In [11]:
lgbm = create_model('lightgbm')

In [ ]:
lgbm_tune = tune_model(lgbm)

In [ ]:
#predict_model(lgbm_tune);
predict_model(lgbm);

In [ ]:
#newpred = predict_model(lgbm_tune, data=data_unseen)
newpred = predict_model(lgbm, data=data_unseen)

In [12]:
et = create_model('et')

In [ ]:
et_tune = tune_model(et)

In [ ]:
predict_model(et_tune);
#predict_model(et);

In [ ]:
#newpred = predict_model(et_tune, data=data_unseen)
newpred = predict_model(et, data=data_unseen)

In [ ]:
xgb = create_model('xgboost')

In [ ]:
xgb_tune = tune_model(xgb)

In [ ]:
#predict_model(xgb_tune);
predict_model(xgb);

In [ ]:
#newpred = predict_model(xgb_tune, data=data_unseen)
newpred = predict_model(xgb, data=data_unseen)

In [ ]:
nb = create_model('nb')

In [ ]:
nb_tune = tune_model(nb)

In [ ]:
#predict_model(nb_tune);
predict_model(nb);

In [ ]:
#newpred = predict_model(nb_tune, data=data_unseen)
newpred = predict_model(nb, data=data_unseen)

In [ ]:
blend1 = blend_models([cat_tune, lgbm])

In [ ]:
blend1_tune = tune_model(blend1)

In [ ]:
predict_model(blend1_tune);
#predict_model(blend1);

In [ ]:
#newpred = predict_model(blend1_tune, data=data_unseen)
newpred = predict_model(blend1, data=data_unseen)

In [ ]:
blend2 = blend_models([cat_tune, et])

In [ ]:
blend2_tune = tune_model(blend2)

In [ ]:
#predict_model(blend2_tune);
predict_model(blend2);

In [ ]:
#newpred = predict_model(blend2_tune, data=data_unseen)
newpred = predict_model(blend2, data=data_unseen)

In [ ]:
blend3 = blend_models([cat_tune, nb])

In [ ]:
blend3_tune = tune_model(blend3)

In [ ]:
predict_model(blend3_tune);
#predict_model(blend3);

In [ ]:
newpred = predict_model(blend3_tune, data=data_unseen)
#newpred = predict_model(blend3, data=data_unseen)

In [ ]:
blend4 = blend_models([cat_tune, et, nb])

In [ ]:
blend4_tune = tune_model(blend4)

In [ ]:
predict_model(blend4_tune);
#predict_model(blend4);

In [ ]:
newpred = predict_model(blend4_tune, data=data_unseen)
#newpred = predict_model(blend4, data=data_unseen)

In [13]:
blend5 = blend_models([cat_tune, lgbm, et])

In [ ]:
blend5_tune = tune_model(blend5)

Initiated  . . . . . . . . . . . . . . . . . .                   20:56:21
Status     . . . . . . . . . . . . . . . . . .  Searching Hyperparameters
Estimator  . . . . . . . . . . . . . . . . . .          Voting Classifier

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits

In [ ]:
#predict_model(blend5_tune);
predict_model(blend5);

In [ ]:
newpred = predict_model(blend5_tune, data=data_unseen)
#newpred = predict_model(blend5, data=data_unseen)

In [ ]:
blend6 = blend_models([rf, et])

In [ ]:
blend6_tune = tune_model(blend6)

In [ ]:
#predict_model(blend6_tune);
predict_model(blend6);

In [ ]:
#newpred = predict_model(blend6_tune, data=data_unseen)
newpred = predict_model(blend6, data=data_unseen)

In [ ]:
blend7 = blend_models([lgbm, xgb])

In [ ]:
blend7_tune = tune_model(blend7)

In [ ]:
predict_model(blend7_tune);
#predict_model(blend7);

In [ ]:
newpred = predict_model(blend7_tune, data=data_unseen)
#newpred = predict_model(blend7, data=data_unseen)

In [ ]:
blend8 = blend_models([cat_tune, rf, lgbm, et, xgb, nb])

In [ ]:
blend8_tune = tune_model(blend8)

In [ ]:
predict_model(blend8_tune);
#predict_model(blend8);

In [ ]:
#newpred = predict_model(blend8_tune, data=data_unseen)
newpred = predict_model(blend8, data=data_unseen)

In [ ]:
save_model(blend5_tune, "LigaMX_model_v2")